//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PersonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Testing.Resources.PersonResources", typeof(PersonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&apos;Isha 
        ///Aarna 
        ///Aarushi 
        ///Aarvi 
        ///Aarya 
        ///Aarzoo 
        ///Aasha 
        ///Aashi 
        ///Aashna 
        ///Aasia 
        ///Aasiya 
        ///Aasiyah 
        ///Aatikah 
        ///Aatiqah 
        ///Aava 
        ///Aaya 
        ///Aayah 
        ///Aayat 
        ///Aaysha 
        ///Aayushi 
        ///Aba 
        ///Abbey 
        ///Abbeygail 
        ///Abbi 
        ///Abbie 
        ///Abbie-Leigh 
        ///Abbie-May 
        ///Abbiegail 
        ///Abbigail 
        ///Abby 
        ///Abbygail 
        ///Abeeha 
        ///Abeera 
        ///Abeerah 
        ///Abena 
        ///Abhia 
        ///Abi 
        ///Abia 
        ///Abida 
        ///Abidemi 
        ///Abigael 
        ///Abigail 
        ///Abigale 
        ///Abigayle 
        ///Abiha 
        ///Abimbola 
        ///Abinaya 
        ///Abiona 
        ///Abisha 
        ///Abisola 
        ///Abrar 
        ///Abygail 
        ///Acacia 
        ///Acelya 
        ///Ada 
        ///Adaeze 
        ///Adalia  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FirstNamesFemale {
            get {
                return ResourceManager.GetString("FirstNamesFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A 
        ///A-Jay 
        ///Aaban 
        ///Aabid 
        ///Aadam 
        ///Aaden 
        ///Aadi 
        ///Aadil 
        ///Aadit 
        ///Aaditya 
        ///Aahil 
        ///Aakash 
        ///Aamer 
        ///Aamil 
        ///Aamir 
        ///Aaqib 
        ///Aaran 
        ///Aarav 
        ///Aaren 
        ///Aarian 
        ///Aarib 
        ///Aarish 
        ///Aariyan 
        ///Aariz 
        ///Aarnav 
        ///Aaron 
        ///Aaron-James 
        ///Aarron 
        ///Aarun 
        ///Aarush 
        ///Aarya 
        ///Aaryan 
        ///Aashir 
        ///Aashish 
        ///Aasim 
        ///Aathavan 
        ///Aayan 
        ///Aayush 
        ///Aban 
        ///Abass 
        ///Abbas 
        ///Abd 
        ///Abdalla 
        ///Abdallah 
        ///Abdalrahman 
        ///Abdel 
        ///Abdelkader 
        ///Abdelrahim 
        ///Abdelrahman 
        ///Abdi 
        ///Abdifatah 
        ///Abdihafid 
        ///Abdihakim 
        ///Abdikarim 
        ///Abdillahi 
        ///Abdimalik  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FirstNamesMale {
            get {
                return ResourceManager.GetString("FirstNamesMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbott
        ///Abrams
        ///Adams
        ///Adcock
        ///Adkins
        ///Adler
        ///Albright
        ///Aldridge
        ///Alexander
        ///Alford
        ///Allen
        ///Allison
        ///Allred
        ///Alston
        ///Anderson
        ///Andrews
        ///Anthony
        ///Archer
        ///Armstrong
        ///Arnold
        ///Arthur
        ///Ashley
        ///Atkins
        ///Atkinson
        ///Austin
        ///Avery
        ///Aycock
        ///Ayers
        ///Bailey
        ///Baird
        ///Baker
        ///Baldwin
        ///Ball
        ///Ballard
        ///Banks
        ///Barbee
        ///Barber
        ///Barbour
        ///Barefoot
        ///Barker
        ///Barnes
        ///Barnett
        ///Barr
        ///Barrett
        ///Barry
        ///Bartlett
        ///Barton
        ///Bass
        ///Batchelor
        ///Bates
        ///Bauer
        ///Baxter
        ///Beach
        ///Bean
        ///Beard
        ///Beasley
        ///Beatty
        ///Beck
        ///Becker
        ///Bell
        ///Bender
        ///Bennett
        ///Benson
        ///Be [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LastNames {
            get {
                return ResourceManager.GetString("LastNames", resourceCulture);
            }
        }
    }
}
