//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Testing.Resources.WebResources", typeof(WebResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to google.com
        ///twitter.com
        ///youtube.com
        ///adobe.com
        ///wordpress.org
        ///blogspot.com
        ///wikipedia.org
        ///godaddy.com
        ///yahoo.com
        ///wordpress.com
        ///w3.org
        ///linkedin.com
        ///amazon.com
        ///flickr.com
        ///myspace.com
        ///apple.com
        ///miibeian.gov.cn
        ///digg.com
        ///microsoft.com
        ///addthis.com
        ///stumbleupon.com
        ///tumblr.com
        ///vimeo.com
        ///macromedia.com
        ///statcounter.com
        ///feedburner.com
        ///qq.com
        ///msn.com
        ///baidu.com
        ///reddit.com
        ///bit.ly
        ///nytimes.com
        ///bbc.co.uk
        ///blogger.com
        ///youtu.be
        ///gov.uk
        ///technorati.com
        ///cnn.com
        ///sourceforge.net
        ///typepad.com
        ///livejour [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Domains {
            get {
                return ResourceManager.GetString("Domains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home
        ///Work
        ///Other.
        /// </summary>
        public static string EmailTypes {
            get {
                return ResourceManager.GetString("EmailTypes", resourceCulture);
            }
        }
    }
}
